# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hugo Med' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hugo Med
  pod 'IGListKit', '~> 4.0.0'

  target 'Hugo MedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hugo MedUITests' do
    # Pods for testing
  end

end
