package com.apps.client.juan.hugomed.service;

public enum MED_API_URL {
    GET_PATIENT_BY_ID,
    GET_COMPANY_CATALOG,
    GET_DOCTORS_BY_MICROUNIVERSE,
    GET_DOCTOR_BY_ID,
    GET_DOCTOR_SERVICES,
    REGISTER_ON_DEMAND_APPOINTMENT,
    GET_PATIENT_APPOINTMENT,
    GET_COMM_KEYS_APPOINTMENT;
    public String param1;
}